#include <algorithm>
#include <array>
#include <charconv>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <unordered_map>
#include <vector>

#include "realperf/CheckPoint.hpp"
#include "realperf/CmdArgs.hpp"

namespace {

struct Options {
    std::string input;
    std::string literal_strings;
    std::uint64_t limit = 0;
    bool include_empty = false;
};

using LiteralStringMap = std::unordered_map<std::uint32_t, std::string>;

[[noreturn]] void usage(std::string_view error = {})
{
    if (!error.empty()) {
        std::cerr << "error: " << error << "\n\n";
    }

    std::cerr
        << "usage: checkpoint_print [options] PATH\n\n"
        << "options:\n"
        << "  -n, --limit N       print at most N checkpoints (default: all non-empty)\n"
        << "  -l, --literals PATH literal string CSV from --dump-literals\n"
        << "      --all           include empty zeroed checkpoint slots\n"
        << "  -h, --help          show this help\n\n"
        << "Prints checkpoint backing files generated by --checkpoint-file.\n";
    std::exit(error.empty() ? 0 : 2);
}

Options parse_options(int argc, char** argv)
{
    Options options;
    realperf::CmdArgs args(argc, argv);

    static constexpr std::array<std::string_view, 8> known_options{
        "h",
        "help",
        "n",
        "limit",
        "l",
        "literals",
        "literal-strings",
        "all",
    };

    for (const auto& [name, value] : args.values()) {
        if (args.is_positional(name)) {
            continue;
        }
        if (std::find(known_options.begin(), known_options.end(), name) == known_options.end()) {
            usage("unknown option " + name);
        }
    }

    if (args.has({"h", "help"})) {
        usage();
    }
    if (const auto name = args.find({"n", "limit"})) {
        options.limit = args.as<std::uint64_t>(*name);
    }
    if (const auto name = args.find({"l", "literals", "literal-strings"})) {
        options.literal_strings = args.as<std::string>(*name);
    }
    options.include_empty = args.has("all");

    if (args.positional_count() == 1) {
        options.input = std::string{args.positional(0)};
    } else if (args.positional_count() > 1) {
        usage("only one input path is supported");
    }

    if (options.input.empty()) {
        usage("missing checkpoint path");
    }

    return options;
}

std::uint32_t parse_fingerprint(std::string_view value, std::size_t line_number)
{
    if (value.empty()) {
        throw std::runtime_error("missing fingerprint in literal CSV at line " + std::to_string(line_number));
    }

    int base = 10;
    if (value.starts_with("0x") || value.starts_with("0X")) {
        value.remove_prefix(2);
        base = 16;
    }
    if (value.empty()) {
        throw std::runtime_error("missing fingerprint in literal CSV at line " + std::to_string(line_number));
    }

    std::uint32_t fingerprint = 0;
    const auto* begin = value.data();
    const auto* end = value.data() + value.size();
    const auto parsed = std::from_chars(begin, end, fingerprint, base);
    if (parsed.ec != std::errc{} || parsed.ptr != end) {
        throw std::runtime_error("invalid fingerprint in literal CSV at line " + std::to_string(line_number));
    }

    return fingerprint;
}

LiteralStringMap read_literal_string_map(const std::string& path)
{
    LiteralStringMap literals;
    if (path.empty()) {
        return literals;
    }

    std::ifstream in(path);
    if (!in) {
        throw std::runtime_error("failed to open literal string CSV: " + path);
    }

    std::string line;
    std::size_t line_number = 0;
    if (!std::getline(in, line)) {
        throw std::runtime_error("literal string CSV is empty: " + path);
    }

    ++line_number;
    if (!line.empty() && line.back() == '\r') {
        line.pop_back();
    }
    if (line != "literal,fingerprint") {
        throw std::runtime_error("literal string CSV header must be literal,fingerprint");
    }

    while (std::getline(in, line)) {
        ++line_number;
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        if (line.empty()) {
            continue;
        }

        const auto comma = line.rfind(',');
        if (comma == std::string::npos || comma == line.size() - 1u) {
            throw std::runtime_error("invalid literal CSV row at line " + std::to_string(line_number));
        }

        std::string literal = line.substr(0, comma);
        const auto fingerprint = parse_fingerprint(std::string_view{line}.substr(comma + 1u), line_number);
        const auto [it, inserted] = literals.emplace(fingerprint, literal);
        if (!inserted && it->second != literal) {
            throw std::runtime_error("literal fingerprint collision in CSV at line " + std::to_string(line_number));
        }
    }

    return literals;
}

const char* type_name(realperf::CheckPoint::Type type)
{
    switch (type) {
    case realperf::CheckPoint::Type::CP_Start:
        return "start";
    case realperf::CheckPoint::Type::CP_Normal:
        return "normal";
    case realperf::CheckPoint::Type::CP_ScopeStart:
        return "scope_start";
    case realperf::CheckPoint::Type::CP_ScopeEnd:
        return "scope_end";
    case realperf::CheckPoint::Type::CP_Order:
        return "order";
    case realperf::CheckPoint::Type::CP_Event:
        return "event";
    case realperf::CheckPoint::Type::CP_Custom:
        return "custom";
    case realperf::CheckPoint::Type::CP_End:
        return "end";
    }

    return "unknown";
}

const char* category_name(realperf::Category category)
{
    switch (category) {
    case realperf::Category::CAT_Default:
        return "default";
    case realperf::Category::CAT_MD:
        return "md";
    case realperf::Category::CAT_Order:
        return "order";
    case realperf::Category::CAT_Strategy:
        return "strategy";
    case realperf::Category::CAT_Event:
        return "event";
    }

    return "unknown";
}

std::string_view literal_text(realperf::LiteralString literal, const LiteralStringMap& literals)
{
    const auto it = literals.find(literal.value());
    if (it != literals.end()) {
        return it->second;
    }

    return {};
}

bool is_empty(const realperf::CheckPoint& checkpoint)
{
    return checkpoint.where_.empty() && checkpoint.tick_ == 0
        && checkpoint.reserved_ == 0
        && static_cast<std::uint8_t>(checkpoint.type_) == 0
        && static_cast<std::uint8_t>(checkpoint.category_) == 0;
}

std::vector<realperf::CheckPoint> read_checkpoints(const std::string& path)
{
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) {
        throw std::runtime_error("failed to open checkpoint file: " + path);
    }

    const auto size = in.tellg();
    if (size < 0) {
        throw std::runtime_error("failed to stat checkpoint file: " + path);
    }
    if (static_cast<std::uint64_t>(size) % sizeof(realperf::CheckPoint) != 0u) {
        throw std::runtime_error("checkpoint file size is not a multiple of CheckPoint size");
    }

    std::vector<realperf::CheckPoint> checkpoints(
        static_cast<std::size_t>(static_cast<std::uint64_t>(size) / sizeof(realperf::CheckPoint)));

    in.seekg(0, std::ios::beg);
    in.read(reinterpret_cast<char*>(checkpoints.data()), size);
    if (in.gcount() != size) {
        throw std::runtime_error("failed to read checkpoint file: " + path);
    }

    return checkpoints;
}

void print_delta(realperf::Tick current, realperf::Tick previous)
{
    if (current >= previous) {
        std::cout << " delta=" << current - previous;
    } else {
        std::cout << " delta=-" << previous - current;
    }
}

void print_checkpoint(std::size_t index,
                      const realperf::CheckPoint& checkpoint,
                      const LiteralStringMap& literals,
                      std::optional<realperf::Tick>& previous_tick)
{
    const auto where = literal_text(checkpoint.where_, literals);

    std::cout << '[' << index << ']'
              << " tick=" << checkpoint.tick_;

    if (previous_tick) {
        print_delta(checkpoint.tick_, *previous_tick);
    }
    previous_tick = checkpoint.tick_;

    std::cout << " type=" << type_name(checkpoint.type_)
              << " category=" << category_name(checkpoint.category_)
              << " reserved=" << checkpoint.reserved_;

    if (!where.empty()) {
        std::cout << " where=\"" << where << '"';
    } else if (!checkpoint.where_.empty()) {
        std::cout << " where_hash=0x"
                  << std::hex << std::setw(6) << std::setfill('0') << checkpoint.where_.value()
                  << std::dec << std::setfill(' ');
    } else {
        std::cout << " where=<empty>";
    }

    std::cout << '\n';
}

void print_checkpoints(const Options& options)
{
    const auto literals = read_literal_string_map(options.literal_strings);
    const auto checkpoints = read_checkpoints(options.input);
    std::uint64_t printed = 0;
    std::optional<realperf::Tick> previous_tick;

    for (std::size_t index = 0; index < checkpoints.size(); ++index) {
        if (!options.include_empty && is_empty(checkpoints[index])) {
            continue;
        }
        if (options.limit != 0 && printed >= options.limit) {
            break;
        }

        print_checkpoint(index, checkpoints[index], literals, previous_tick);
        ++printed;
    }

    std::cerr << "printed " << printed << " checkpoint";
    if (printed != 1) {
        std::cerr << 's';
    }
    std::cerr << " from " << checkpoints.size() << " slots\n";
}

} // namespace

int main(int argc, char** argv)
{
    try {
        const auto options = parse_options(argc, argv);
        print_checkpoints(options);
    } catch (const std::exception& ex) {
        std::cerr << "checkpoint_print: " << ex.what() << '\n';
        return 1;
    }

    return 0;
}
