#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include "realperf/CheckPoint.hpp"
#include "realperf/CmdArgs.hpp"
#include "realperf/RingBuffer.hpp"
#include "realperf/itch5.hpp"

namespace {

constexpr std::size_t kPcapGlobalHeaderSize = 24;
constexpr std::size_t kPcapPacketHeaderSize = 16;
constexpr std::size_t kEthernetHeaderSize = 14;
constexpr std::size_t kIpv4MinHeaderSize = 20;
constexpr std::size_t kUdpHeaderSize = 8;
constexpr std::size_t kDefaultCheckpointCapacity = 1u << 20;

struct Options {
    std::string input;
    std::uint32_t limit = 0;
    std::string checkpoint_file;
    std::size_t checkpoint_capacity = kDefaultCheckpointCapacity;
};

struct Cursor {
    const std::uint8_t* data = nullptr;
    std::size_t size = 0;
    std::size_t offset = 0;

    [[nodiscard]] std::size_t remaining() const
    {
        return size - offset;
    }

    void require(std::size_t bytes) const
    {
        if (remaining() < bytes) {
            throw std::runtime_error("truncated packet data");
        }
    }

    std::uint8_t u8()
    {
        require(1);
        return data[offset++];
    }

    std::uint16_t u16_be()
    {
        require(2);
        const auto value = static_cast<std::uint16_t>((data[offset] << 8) | data[offset + 1]);
        offset += 2;
        return value;
    }

    std::uint32_t u32_be()
    {
        require(4);
        const auto value = (static_cast<std::uint32_t>(data[offset]) << 24)
                         | (static_cast<std::uint32_t>(data[offset + 1]) << 16)
                         | (static_cast<std::uint32_t>(data[offset + 2]) << 8)
                         | static_cast<std::uint32_t>(data[offset + 3]);
        offset += 4;
        return value;
    }

    std::uint64_t u48_be()
    {
        require(6);
        std::uint64_t value = 0;
        for (int i = 0; i < 6; ++i) {
            value = (value << 8) | data[offset + i];
        }
        offset += 6;
        return value;
    }

    std::uint64_t u64_be()
    {
        require(8);
        std::uint64_t value = 0;
        for (int i = 0; i < 8; ++i) {
            value = (value << 8) | data[offset + i];
        }
        offset += 8;
        return value;
    }

    std::string ascii(std::size_t bytes)
    {
        require(bytes);
        std::string text(reinterpret_cast<const char*>(data + offset), bytes);
        offset += bytes;
        return text;
    }

    void skip(std::size_t bytes)
    {
        require(bytes);
        offset += bytes;
    }
};

[[noreturn]] void usage(std::string_view error = {})
{
    if (!error.empty()) {
        std::cerr << "error: " << error << "\n\n";
    }

    std::cerr
        << "usage: pcap_itch_print [options] PATH\n\n"
        << "options:\n"
        << "  -n, --limit N       print at most N packets (default: all)\n"
        << "      --checkpoint-file PATH\n"
        << "                      file-backed checkpoint ring buffer path\n"
        << "      --checkpoint-capacity N\n"
        << "                      checkpoint record capacity (default: 1048576)\n"
        << "  -h, --help          show this help\n\n"
        << "Prints Ethernet/IPv4/UDP PCAP files carrying MoldUDP64-wrapped Nasdaq\n"
        << "ITCH 5.0-style messages generated by pcap_itch_gen.\n";
    std::exit(error.empty() ? 0 : 2);
}

Options parse_options(int argc, char** argv)
{
    Options options;
    realperf::CmdArgs args(argc, argv);

    static constexpr std::array<std::string_view, 6> known_options{
        "h",
        "help",
        "n",
        "limit",
        "checkpoint-file",
        "checkpoint-capacity",
    };

    for (const auto& [name, value] : args.values()) {
        if (args.is_positional(name)) {
            continue;
        }
        if (std::find(known_options.begin(), known_options.end(), name) == known_options.end()) {
            usage("unknown option " + name);
        }
    }

    if (args.has({"h", "help"})) {
        usage();
    }
    if (const auto name = args.find({"n", "limit"})) {
        options.limit = args.as<std::uint32_t>(*name);
    }
    if (args.has("checkpoint-file")) {
        options.checkpoint_file = args.as<std::string>("checkpoint-file");
    }
    if (args.has("checkpoint-capacity")) {
        options.checkpoint_capacity = args.as<std::size_t>("checkpoint-capacity");
    }

    if (options.input.empty()) {
        if (args.positional_count() == 1) {
            options.input = std::string{args.positional(0)};
        } else if (args.positional_count() > 1) {
            usage("only one input path is supported");
        }
    }

    if (options.input.empty()) {
        usage("missing input pcap path");
    }
    return options;
}

std::optional<realperf::RingBuffer<realperf::CheckPoint>> init_checkpoint_recorder(const Options& options)
{
    if (options.checkpoint_file.empty()) {
        return std::nullopt;
    }

    std::optional<realperf::RingBuffer<realperf::CheckPoint>> buffer;
    buffer.emplace(options.checkpoint_capacity, options.checkpoint_file);
    REALPERF_RECORDER_INIT(buffer->data(), buffer->data() + buffer->capacity(), 1u);
    return buffer;
}

std::uint16_t read_u16_le(const std::array<std::uint8_t, kPcapGlobalHeaderSize>& bytes,
                          std::size_t offset)
{
    return static_cast<std::uint16_t>(bytes[offset] | (bytes[offset + 1] << 8));
}

std::uint32_t read_u32_le(const std::uint8_t* bytes)
{
    return static_cast<std::uint32_t>(bytes[0])
         | (static_cast<std::uint32_t>(bytes[1]) << 8)
         | (static_cast<std::uint32_t>(bytes[2]) << 16)
         | (static_cast<std::uint32_t>(bytes[3]) << 24);
}

std::uint32_t read_u32_be(const std::uint8_t* bytes)
{
    return (static_cast<std::uint32_t>(bytes[0]) << 24)
         | (static_cast<std::uint32_t>(bytes[1]) << 16)
         | (static_cast<std::uint32_t>(bytes[2]) << 8)
         | static_cast<std::uint32_t>(bytes[3]);
}

std::string ipv4_string(const std::uint8_t* bytes)
{
    return std::to_string(bytes[0]) + "."
         + std::to_string(bytes[1]) + "."
         + std::to_string(bytes[2]) + "."
         + std::to_string(bytes[3]);
}

void print_itch_message(std::uint16_t message_index,
                        Cursor message)
{
    REALPERF_SCOPE("pcap_itch_print::print_itch_message", realperf::Category::CAT_MD);

    const auto decoded = realperf::itch5::parse_message(message.data, message.size);

    REALPERF_CHECKPOINT("pcap_itch_print::print_itch_message:print");
    std::cout << "    msg[" << message_index << "] " << decoded;

    if (decoded.extra_bytes != 0) {
        std::cout << " extra_bytes=" << decoded.extra_bytes;
    }
    std::cout << '\n';
}

void print_packet(std::uint32_t packet_index,
                  std::uint32_t ts_sec,
                  std::uint32_t ts_usec,
                  const std::vector<std::uint8_t>& packet)
{
    REALPERF_START("pcap_itch_print::print_packet");

    if (packet.size() < kEthernetHeaderSize + kIpv4MinHeaderSize + kUdpHeaderSize + realperf::itch5::kMoldUdp64HeaderSize) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " is too small");
    }

    Cursor cursor{packet.data(), packet.size(), 0};
    cursor.skip(12);
    const auto ether_type = cursor.u16_be();
    if (ether_type != 0x0800) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " is not IPv4");
    }

    const auto version_ihl = cursor.u8();
    const auto version = version_ihl >> 4;
    const auto ihl = static_cast<std::size_t>(version_ihl & 0x0f) * 4;
    if (version != 4 || ihl < kIpv4MinHeaderSize) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " has invalid IPv4 header");
    }
    cursor.skip(1);
    const auto total_length = cursor.u16_be();
    cursor.skip(5);
    const auto protocol = cursor.u8();
    cursor.skip(2);
    const auto src_ip_offset = cursor.offset;
    cursor.skip(4);
    const auto dst_ip_offset = cursor.offset;
    cursor.skip(4);
    if (protocol != 17) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " is not UDP");
    }
    if (ihl > kIpv4MinHeaderSize) {
        cursor.skip(ihl - kIpv4MinHeaderSize);
    }

    const auto src_port = cursor.u16_be();
    const auto dst_port = cursor.u16_be();
    const auto udp_length = cursor.u16_be();
    cursor.skip(2);
    if (udp_length < kUdpHeaderSize) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " has invalid UDP length");
    }
    const auto udp_payload_size = static_cast<std::size_t>(udp_length) - kUdpHeaderSize;
    if (cursor.remaining() < udp_payload_size) {
        throw std::runtime_error("packet " + std::to_string(packet_index) + " has truncated UDP payload");
    }

    REALPERF_CHECKPOINT("pcap_itch_print::print_packet:print_payload");
    Cursor payload{packet.data() + cursor.offset, udp_payload_size, 0};
    const auto session = payload.ascii(10);
    const auto sequence = payload.u64_be();
    const auto message_count = payload.u16_be();

    std::cout << "packet " << packet_index
              << " ts=" << ts_sec << '.' << std::setfill('0') << std::setw(6) << ts_usec << std::setfill(' ')
              << " caplen=" << packet.size()
              << " ip_total=" << total_length
              << " " << ipv4_string(packet.data() + src_ip_offset) << ':' << src_port
              << " -> " << ipv4_string(packet.data() + dst_ip_offset) << ':' << dst_port
              << " session=" << session
              << " seq=" << sequence
              << " messages=" << message_count
              << '\n';

    for (std::uint16_t i = 0; i < message_count; ++i) {
        const auto length = payload.u16_be();
        payload.require(length);
        Cursor message{payload.data + payload.offset, length, 0};
        print_itch_message(i, message);
        payload.skip(length);
    }
}

void print_pcap(const Options& options)
{
    REALPERF_SCOPE("pcap_itch_print::print_pcap", realperf::Category::CAT_MD);

    std::ifstream in(options.input, std::ios::binary);
    if (!in) {
        throw std::runtime_error("failed to open input file: " + options.input);
    }

    std::array<std::uint8_t, kPcapGlobalHeaderSize> global{};
    in.read(reinterpret_cast<char*>(global.data()), static_cast<std::streamsize>(global.size()));
    if (in.gcount() != static_cast<std::streamsize>(global.size())) {
        throw std::runtime_error("truncated pcap global header");
    }

    const auto magic_le = read_u32_le(global.data());
    const auto magic_be = read_u32_be(global.data());
    if (magic_le != 0xa1b2c3d4) {
        if (magic_be == 0xa1b2c3d4) {
            throw std::runtime_error("big-endian pcap files are not supported yet");
        }
        throw std::runtime_error("not a classic pcap file");
    }
    if (read_u16_le(global, 4) != 2 || read_u16_le(global, 6) != 4) {
        throw std::runtime_error("unsupported pcap version");
    }
    const auto link_type = read_u32_le(global.data() + 20);
    if (link_type != 1) {
        throw std::runtime_error("pcap link type is not Ethernet");
    }

    std::uint32_t packet_index = 0;
    while (!options.limit || packet_index < options.limit) {
        std::array<std::uint8_t, kPcapPacketHeaderSize> header{};
        in.read(reinterpret_cast<char*>(header.data()), static_cast<std::streamsize>(header.size()));
        if (in.gcount() == 0) {
            break;
        }
        if (in.gcount() != static_cast<std::streamsize>(header.size())) {
            throw std::runtime_error("truncated pcap packet header");
        }

        const auto ts_sec = read_u32_le(header.data());
        const auto ts_usec = read_u32_le(header.data() + 4);
        const auto caplen = read_u32_le(header.data() + 8);
        const auto origlen = read_u32_le(header.data() + 12);
        if (caplen != origlen) {
            std::cout << "packet " << packet_index << " is captured short: caplen="
                      << caplen << " origlen=" << origlen << '\n';
        }

        std::vector<std::uint8_t> packet(caplen);
        in.read(reinterpret_cast<char*>(packet.data()), static_cast<std::streamsize>(packet.size()));
        if (in.gcount() != static_cast<std::streamsize>(packet.size())) {
            throw std::runtime_error("truncated pcap packet data");
        }

        print_packet(packet_index, ts_sec, ts_usec, packet);
        REALPERF_COMMIT();
        ++packet_index;
    }
}

} // namespace

int main(int argc, char** argv)
{
    try {
        const auto options = parse_options(argc, argv);
        [[maybe_unused]] auto checkpoint_buffer = init_checkpoint_recorder(options);
        print_pcap(options);
        REALPERF_COMMIT();
    } catch (const std::exception& ex) {
        REALPERF_COMMIT();
        std::cerr << "pcap_itch_print: " << ex.what() << '\n';
        return 1;
    }

    return 0;
}
